package report

import (
	"bytes"
	"fmt"
	"log"
	"strconv"
	"strings"

	"github.com/jung-kurt/gofpdf"
	"github.com/sbom-io/api/internal/compliance"
	"github.com/sbom-io/api/internal/scanner"
)

type ScanInfo struct {
	ID          string
	RepoName    string
	RepoURL     string
	Ecosystem   string
	GeneratedAt string
}

type VulnSummary struct {
	Critical int
	High     int
	Medium   int
	Low      int
}

type ReportVuln struct {
	Package  string
	Version  string
	CVEID    string
	Severity string
	Summary  string
}

func GeneratePDFReport(scan ScanInfo, components []scanner.Package, vulnSummary VulnSummary, topVulns []ReportVuln, ntia compliance.NTIAResult) ([]byte, error) {
	log.Printf("NTIA elements count: %d, score: %d", len(ntia.Elements), ntia.Score)
	pdf := gofpdf.New("P", "mm", "A4", "")

	// --- PAGE 1: Cover ---
	pdf.AddPage()
	pdf.SetFont("Helvetica", "B", 36)
	pdf.SetTextColor(30, 30, 30)
	pdf.CellFormat(190, 30, "SBOM.io", "", 1, "C", false, 0, "")

	pdf.SetFont("Helvetica", "B", 24)
	pdf.CellFormat(190, 20, "Software Bill of Materials", "", 1, "C", false, 0, "")
	pdf.CellFormat(190, 20, "Compliance Report", "", 1, "C", false, 0, "")

	pdf.Ln(20)
	pdf.SetFont("Helvetica", "", 16)
	pdf.CellFormat(190, 10, fmt.Sprintf("Repository: %s", scan.RepoName), "", 1, "C", false, 0, "")
	pdf.SetFont("Helvetica", "", 12)
	pdf.CellFormat(190, 10, fmt.Sprintf("Generated: %s", scan.GeneratedAt), "", 1, "C", false, 0, "")
	pdf.Ln(10)

	pdf.Line(20, pdf.GetY(), 190, pdf.GetY())
	pdf.Ln(20)

	pdf.SetFont("Helvetica", "B", 14)
	pdf.CellFormat(63, 10, "Components", "", 0, "C", false, 0, "")
	pdf.CellFormat(64, 10, "Critical CVEs", "", 0, "C", false, 0, "")
	pdf.CellFormat(63, 10, "NTIA Score", "", 1, "C", false, 0, "")

	pdf.SetFont("Helvetica", "", 18)
	pdf.CellFormat(63, 10, strconv.Itoa(len(components)), "", 0, "C", false, 0, "")
	
	if vulnSummary.Critical > 0 {
		pdf.SetTextColor(220, 50, 50)
	}
	pdf.CellFormat(64, 10, strconv.Itoa(vulnSummary.Critical), "", 0, "C", false, 0, "")
	pdf.SetTextColor(30, 30, 30)

	if ntia.Compliant {
		pdf.SetTextColor(50, 180, 100)
	} else {
		pdf.SetTextColor(220, 50, 50)
	}
	pdf.CellFormat(63, 10, fmt.Sprintf("%d/100", ntia.Score), "", 1, "C", false, 0, "")
	pdf.SetTextColor(30, 30, 30)

	pdf.SetY(270)
	pdf.SetFont("Helvetica", "I", 10)
	pdf.SetTextColor(120, 120, 120)
	pdf.CellFormat(190, 10, "Generated by SBOM.io - Automated SBOM Compliance Platform", "", 1, "C", false, 0, "")

	// --- PAGE 2: NTIA Compliance ---
	pdf.AddPage()
	pdf.SetTextColor(30, 30, 30)
	pdf.SetFont("Helvetica", "B", 18)
	pdf.CellFormat(190, 10, "NTIA Minimum Elements Assessment", "", 1, "L", false, 0, "")
	pdf.SetFont("Helvetica", "", 12)
	pdf.SetTextColor(100, 100, 100)
	pdf.CellFormat(190, 8, "US Executive Order 14028 Compliance", "", 1, "L", false, 0, "")
	pdf.Ln(5)

	if ntia.Compliant {
		pdf.SetFillColor(50, 180, 100)
	} else {
		pdf.SetFillColor(220, 50, 50)
	}
	pdf.SetTextColor(255, 255, 255)
	pdf.SetFont("Helvetica", "B", 14)
	statusText := "NON-COMPLIANT"
	if ntia.Compliant {
		statusText = "COMPLIANT"
	}
	pdf.CellFormat(190, 10, fmt.Sprintf(" NTIA Status: %s", statusText), "", 1, "L", true, 0, "")

	pdf.Ln(2)
	euCompliant := compliance.CheckEUCRA(ntia)
	if euCompliant {
		pdf.SetFillColor(50, 180, 100)
		statusText = "COMPLIANT"
	} else {
		pdf.SetFillColor(220, 50, 50)
		statusText = "NON-COMPLIANT"
	}
	pdf.CellFormat(190, 10, fmt.Sprintf(" EU CRA Status: %s", statusText), "", 1, "L", true, 0, "")

	pdf.Ln(10)
	pdf.SetTextColor(30, 30, 30)

	pdf.SetFont("Helvetica", "B", 10)
	pdf.SetFillColor(220, 220, 220)
	pdf.CellFormat(45, 8, "Element Name", "1", 0, "L", true, 0, "")
	pdf.CellFormat(25, 8, "Status", "1", 0, "C", true, 0, "")
	pdf.CellFormat(20, 8, "Cov %", "1", 0, "C", true, 0, "")
	pdf.CellFormat(100, 8, "Detail", "1", 1, "L", true, 0, "")

	pdf.SetFont("Helvetica", "", 9)
	for i, el := range ntia.Elements {
		if i%2 == 0 {
			pdf.SetFillColor(245, 245, 245)
		} else {
			pdf.SetFillColor(255, 255, 255)
		}

		status := "FAIL"
		if el.Passed {
			status = "PASS"
		}
		pdf.CellFormat(45, 8, " "+el.Name, "1", 0, "L", true, 0, "")
		
		if el.Passed {
			pdf.SetTextColor(50, 180, 100)
		} else {
			pdf.SetTextColor(220, 50, 50)
		}
		pdf.CellFormat(25, 8, status, "1", 0, "C", true, 0, "")
		pdf.SetTextColor(30, 30, 30)
		
		pdf.CellFormat(20, 8, fmt.Sprintf("%d%%", el.Coverage), "1", 0, "C", true, 0, "")
		
		detailSnippet := el.Detail
		if len(detailSnippet) > 55 {
			detailSnippet = detailSnippet[:52] + "..."
		}
		pdf.CellFormat(100, 8, " "+detailSnippet, "1", 1, "L", true, 0, "")
	}

	if len(ntia.Recommendations) > 0 {
		pdf.Ln(10)
		pdf.SetFont("Helvetica", "B", 12)
		pdf.CellFormat(190, 8, "Recommendations", "", 1, "L", false, 0, "")
		pdf.SetFont("Helvetica", "", 10)
		for _, rec := range ntia.Recommendations {
			pdf.MultiCell(190, 6, "* "+rec, "", "L", false)
		}
	}

	// --- PAGE 3: Vulnerabilities ---
	pdf.AddPage()
	pdf.SetTextColor(30, 30, 30)
	pdf.SetFont("Helvetica", "B", 18)
	pdf.CellFormat(190, 10, "Security Vulnerability Report", "", 1, "L", false, 0, "")
	pdf.Ln(5)

	boxW := 47.5
	pdf.SetFont("Helvetica", "B", 12)
	pdf.SetFillColor(220, 50, 50)
	pdf.SetTextColor(255, 255, 255)
	pdf.CellFormat(boxW, 8, "Critical", "1", 0, "C", true, 0, "")
	pdf.SetFillColor(230, 120, 50)
	pdf.CellFormat(boxW, 8, "High", "1", 0, "C", true, 0, "")
	pdf.SetFillColor(230, 180, 50)
	pdf.CellFormat(boxW, 8, "Medium", "1", 0, "C", true, 0, "")
	pdf.SetFillColor(100, 150, 200)
	pdf.CellFormat(boxW, 8, "Low", "1", 1, "C", true, 0, "")

	pdf.SetFont("Helvetica", "", 16)
	pdf.SetTextColor(30, 30, 30)
	pdf.CellFormat(boxW, 12, strconv.Itoa(vulnSummary.Critical), "1", 0, "C", false, 0, "")
	pdf.CellFormat(boxW, 12, strconv.Itoa(vulnSummary.High), "1", 0, "C", false, 0, "")
	pdf.CellFormat(boxW, 12, strconv.Itoa(vulnSummary.Medium), "1", 0, "C", false, 0, "")
	pdf.CellFormat(boxW, 12, strconv.Itoa(vulnSummary.Low), "1", 1, "C", false, 0, "")

	pdf.Ln(10)
	
	if len(topVulns) > 0 {
		pdf.SetFont("Helvetica", "B", 10)
		pdf.SetFillColor(220, 220, 220)
		pdf.CellFormat(40, 8, "Package", "1", 0, "L", true, 0, "")
		pdf.CellFormat(20, 8, "Version", "1", 0, "L", true, 0, "")
		pdf.CellFormat(35, 8, "CVE ID", "1", 0, "L", true, 0, "")
		pdf.CellFormat(20, 8, "Severity", "1", 0, "L", true, 0, "")
		pdf.CellFormat(75, 8, "Summary", "1", 1, "L", true, 0, "")

		pdf.SetFont("Helvetica", "", 8)
		for _, v := range topVulns {
			sev := strings.ToUpper(v.Severity)
			if sev == "CRITICAL" {
				pdf.SetFillColor(255, 200, 200) // light red
			} else if sev == "HIGH" {
				pdf.SetFillColor(255, 220, 180) // light orange
			} else {
				pdf.SetFillColor(255, 255, 255)
			}

			sum := v.Summary
			if len(sum) > 40 {
				sum = sum[:37] + "..."
			}

			pdf.CellFormat(40, 6, " "+v.Package, "1", 0, "L", true, 0, "")
			pdf.CellFormat(20, 6, " "+v.Version, "1", 0, "L", true, 0, "")
			pdf.CellFormat(35, 6, " "+v.CVEID, "1", 0, "L", true, 0, "")
			pdf.CellFormat(20, 6, " "+sev, "1", 0, "L", true, 0, "")
			pdf.CellFormat(75, 6, " "+sum, "1", 1, "L", true, 0, "")
		}
	}

	// --- PAGE 4: Components ---
	pdf.AddPage()
	pdf.SetTextColor(30, 30, 30)
	pdf.SetFont("Helvetica", "B", 18)
	dispCount := len(components)
	if dispCount > 100 {
		dispCount = 100
	}
	pdf.CellFormat(190, 10, fmt.Sprintf("Component Inventory (showing %d of %d)", dispCount, len(components)), "", 1, "L", false, 0, "")
	pdf.Ln(5)

	pdf.SetFont("Helvetica", "B", 10)
	pdf.SetFillColor(220, 220, 220)
	pdf.CellFormat(10, 8, "#", "1", 0, "C", true, 0, "")
	pdf.CellFormat(60, 8, "Package Name", "1", 0, "L", true, 0, "")
	pdf.CellFormat(30, 8, "Version", "1", 0, "L", true, 0, "")
	pdf.CellFormat(50, 8, "License", "1", 0, "L", true, 0, "")
	pdf.CellFormat(25, 8, "Ecosystem", "1", 0, "C", true, 0, "")
	pdf.CellFormat(15, 8, "Depth", "1", 1, "C", true, 0, "")

	pdf.SetFont("Helvetica", "", 9)
	for i := 0; i < dispCount; i++ {
		c := components[i]
		if i%2 == 0 {
			pdf.SetFillColor(245, 245, 245)
		} else {
			pdf.SetFillColor(255, 255, 255)
		}

		pdf.CellFormat(10, 6, strconv.Itoa(i+1), "1", 0, "C", true, 0, "")
		pdf.CellFormat(60, 6, " "+c.Name, "1", 0, "L", true, 0, "")
		pdf.CellFormat(30, 6, " "+c.Version, "1", 0, "L", true, 0, "")
		
		lic := c.License
		if len(lic) > 25 { lic = lic[:22]+"..." }
		pdf.CellFormat(50, 6, " "+lic, "1", 0, "L", true, 0, "")
		
		pdf.CellFormat(25, 6, c.Ecosystem, "1", 0, "C", true, 0, "")
		pdf.CellFormat(15, 6, strconv.Itoa(c.Depth), "1", 1, "C", true, 0, "")
	}

	pdf.Ln(10)
	pdf.SetFont("Helvetica", "I", 10)
	pdf.SetTextColor(120, 120, 120)
	pdf.CellFormat(190, 8, "Full inventory available in CycloneDX/SPDX export", "", 1, "C", false, 0, "")

	var buf bytes.Buffer
	err := pdf.Output(&buf)
	if err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}
